/*
* generated by Xtext
*/
package org.apache.ant.antdsl.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class AntDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
