/*
* generated by Xtext
*/
package org.apache.ant.antdsl.xtext.ui.contentassist;

import org.apache.ant.antdsl.xtext.ui.contentassist.AbstractAntDSLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AntDSLProposalProvider extends AbstractAntDSLProposalProvider {

}
