/*
 * generated by Xtext
 */
package org.apache.ant.antdsl.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AntDSLUiModule extends org.apache.ant.antdsl.xtext.ui.AbstractAntDSLUiModule {
	public AntDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
