/*
 * generated by Xtext
 */
package org.apache.ant.antdsl.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AntDSLRuntimeModule extends org.apache.ant.antdsl.xtext.AbstractAntDSLRuntimeModule {

}
